### ISSUE TITLE
Generated Dag File Attempts to Import Older CLI Methods "get_config, create_catalog, create_pipeline"

### ISSUE THREAD

**Issue by makennedy626** [quantumblacklabs/kedro-airflow#21]
## Description
The command kedro airflow deploy generates a dag file that contains the following odd imports:
`# fmt: off`
`# from kedro.cli.cli import <lambda> as get_config  # isort:skip`
`# from kedro.cli.cli import <lambda> as create_catalog  # isort:skip`
`# from kedro.cli.cli import <lambda> as create_pipeline  # isort:skip`
`# fmt: on`

in dag_template.py, I can see that it is grabbing from what appears to be a cookie cutter template:
```bash
# fmt: off
{{import_get_config}}  # isort:skip
{{import_create_catalog}}  # isort:skip
{{import_create_pipeline}}  # isort:skip
# fmt: on
```

With Kedro 0.15.0, run.py uses 
```bash
context = ProjectContext(Path.cwd(), env)
context.run(tags, runner, node_names, from_nodes, to_nodes)
```

Should the dag file not be updated to use context instead? I have implemented my own workaround but am not sure if it is best practice. It works for now, though.

## Context
How has this bug affected you? What were you trying to accomplish?
This originally prevented me from utilizing kedro-airflow. However, my workaround of importing ConfigLoader, DataCatalog, and my src.project.run create_pipeline has allowed me to continue on.

## Steps to Reproduce

1. kedro airflow deploy
2. Go look at /airflow/dags

## Expected Result
Dag file should import the configuration in a way that is up-to-date with Kedro 0.15.0.

## Actual Result
Tell us what happens instead.

`# fmt: off`
`# from kedro.cli.cli import <lambda> as get_config  # isort:skip`
`# from kedro.cli.cli import <lambda> as create_catalog  # isort:skip`
`# from kedro.cli.cli import <lambda> as create_pipeline  # isort:skip`
`# fmt: on`

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment you experienced the bug in:

* Kedro-Airflow plugin version used (get it by running `pip show kedro-airflow`):
* Airflow version (`airflow --version`): 0.1.0
* Kedro version used (`pip show kedro` or `kedro -V`): 0.15.0
* Python version used (`python -V`): 3.6.9
* Operating system and version: Ubuntu 18.04.3 LTS

**Comment by 921kiyo** [comment]
@makennedy626 Thank you for reporting this! You are correct that since Kedro 0.15.0 all of above can be accessed from Kedro 0.15.0. We will update this in the next release :)

**Comment by makennedy626** [comment]
@921kiyo is there a suggested workaround for it? 

This is what I'm currently doing:

```bash
from kedro.config import ConfigLoader

conf_paths = ['conf/base', 'conf/local']
conf_loader = ConfigLoader(conf_paths)
conf_catalog = conf_loader.get('catalog*', 'catalog*/**')

...

from src.<project>.run import create_pipeline as create_pipeline

...

from kedro.io import DataCatalog
config = conf_loader
conf_creds = conf_loader.get('credentials*', 'credentials*/**')
data_catalog = DataCatalog.from_config(catalog=conf_catalog, credentials=conf_creds)
pipeline = create_pipeline()


```

**Comment by 921kiyo** [comment]
@makennedy626 Old way of accessing to context should work since we have backward compatibility in https://github.com/quantumblacklabs/kedro/blob/develop/kedro/cli/cli.py#L550-L561. Are you getting any error with the old way (get_config etc) ?

**Comment by makennedy626** [comment]
@921kiyo After 'kedro airflow create' and changing the '<lambda>' references to their respective calls (get_config, etc.), my airflow UI gives - Broken DAG: [/home/<project>/airflow/dags/<module>_dag.py] cannot import name 'get_config'

**Comment by 921kiyo** [comment]
@makennedy626 We have fixed it in https://github.com/quantumblacklabs/kedro-airflow/pull/22, and will release a patch soon.  I am closing this ticket, and thank you for your contribution to Kedro :)
