### ISSUE TITLE
Log messages in DAG list

### ISSUE THREAD

**Issue by KirtikumarShinde** [quantumblacklabs/kedro-airflow#34]
## Description
Kedro DAG pipeline messages displayed for Airflow commands.

## Context
I used this for creating a Kedro DAG.

## Steps to Reproduce

1. Any sample pipeline for Kedro.
2. Do the Kedro Airflow Create and then Deploy
3. Run the command 'airflow list_dags' - this would display log messages from Kedro pipeline like pipeline completed.

## Expected Result
List DAGs should only list DAGs without any log messages from kedro pipeline.

## Actual Result
Output of Airflow list_dags shows - Pipeline execution completed successfully.

## Your Environment
Include as many relevant details about the environment you experienced the bug in:

* Kedro-Airflow plugin version used (get it by running `pip show kedro-airflow`): 0.2.1
* Airflow version (`airflow --version`): 1.10.6
* Kedro version used (`pip show kedro` or `kedro -V`): 0.15.4
* Python version used (`python -V`): 3.6.9
* Operating system and version: Linux

**Comment by 921kiyo** [comment]
Hi @KirtikumarShinde 
Thank you for reporting the issue! It is due to the fact that `AirflowRunner` class is inheriting from `AbstractRunner` (even though it doesn't really run anything). We will remove the reference to  `AbstractRunner` so the log should go away.

**Comment by KirtikumarShinde** [comment]
Hi @921kiyo does this mean next version it would be fixed? Also just noticed the Airflow UI does not show kedo DAGs, the command lists it, but the UI does not show it. This must be to do with kedro PY file which is added as DAG. Happy to discuss it in office.
