### ISSUE TITLE
Error in default dag file: "TypeError: load() takes 2 positional arguments but 3 were given"

### ISSUE THREAD

**Issue by Dr-DaDe** [quantumblacklabs/kedro-airflow#40]
Hi,

after creating a default dag using "kedro airflow create", running the dag file with airflow returns with the following error:

```
  File ...airflow/dags/base_json_pipeline_dag.py", line 75, in process_context
    data_catalog.load("parameters", parameters)
TypeError: load() takes 2 positional arguments but 3 were given
```

Checking the dag file, I observed the following lines of code
```
...
    parameters = data_catalog.load("parameters")
    parameters["airflow_ds"] = airflow_context["ds"]
    data_catalog.load("parameters", parameters) 
...
```

I believe the last line should read .save(...) instead of .load(...). At least the file runs through if I change these lines by hand and it would make sense in the context of these lines.

If this is the case, it should be updated in [kedro_airflow/dag_template.py](https://github.com/quantumblacklabs/kedro-airflow/blob/develop/kedro_airflow/dag_template.py)

**Comment by 921kiyo** [comment]
@Dr-DaDe Sorry for late response. I confirm that I'm getting the same error. We will fix this :)

**Comment by 921kiyo** [comment]
Fixed in https://github.com/quantumblacklabs/kedro-airflow/pull/45
