### ISSUE TITLE
Request: support for ParallelRunner and MemoryDataSet

### ISSUE THREAD

**Issue by Minyus** [quantumblacklabs/kedro-airflow#41]
## Description
Current version of Kedro-Airflow, which converts a Kedro pipeline to Airflow Python operators, 
cannot get the best out of Kedro.
Especially, `ParallelRunner` and `MemoryDataSet` are not supported.

## Context
I would like to use (almost) all the features of Kedro.

## Possible Implementation

I would suggest to add an Airflow Operator that takes the Kedro project path and Pipeline name (`__default__` in default) as the arguments and runs the Kedro pipeline.

I would call this Airflow Operator "KedroSubDagOperator" since it works similar to Airflow's `SubDagOperator`.

**Comment by 921kiyo** [comment]
Hi @Minyus sorry for late in response, and thank you for raising this! 
As you know, the current implementation is that we take all kedro node and each of them becomes a PythonOperator in Airflow. And running the DAG is done by Airflow, which is parallel. 

Could you explain a bit more about using Kedro `ParallelRunner` with Airflow operator? Are you facing any problem with Airflow parallelism and running your Kedro node?

For `MemoryDataSet`, am I correct that the pain point is that all the datasets have to be registered in `catalog.yml` for the plugin to work? You want to convert your Kedro pipeline into Airflow Dags even when some of the datasets are not specified in catalog.yml?

**Comment by Minyus** [comment]
Hi @921kiyo , thank you for your response.  

I'm just exploring the best practice to seamlessly deploy Kedro pipeline to production using Airflow. 

I see. Now I understand that parallel execusion is supported by Airflow engine rather than Kedro.

Yes, it would be convenient if Kedro pipeline can be converted into Airflow Dags even some datasets are not specified in catalog.yml, but unfortunately Airflow does not seem to support the feature equivalent to MemoryDataSet.

As this issue seems to be rather Airflow's issue, let me close this issue.
Thank you.
