### ISSUE TITLE
[KED-1709] Hello-world demo Docker image for kedro-airflow

### ISSUE THREAD

**Issue by Minyus** [quantumblacklabs/kedro-airflow#56]
## Description

I would suggest uploading a dockerfile in this GitHub repository and a Docker image in DockerHub so users can easily try `kedro-airflow`.

## Context
It is important for potential users to easily try `kedro-airflow` to review how much production-ready Kedro is. 

## Possible Implementation

@vananhlebarca 's work might be helpful.

- https://github.com/vananhlebarca/airflow-dags
- https://hub.docker.com/r/vananhlebarca/docker-airflow-kedro

**Comment by 921kiyo** [comment]
Hi @Minyus Thank you for the suggestion! I've logged this request and will discuss with the team :)

**Comment by Minyus** [comment]
Thank you @921kiyo !

**Comment by lorenabalan** [comment]
Hi @Minyus thanks for the suggestion. We've decided to de-prioritise this in favour of deployment strategy docs added on kedro, but might revisit at a later stage.
