### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by ellis** [quantumblacklabs/kedro-airflow#62]
## Description

kedro-airflow does not install when using python 3.8, e.g.:

```
$ pip install kedro-airflow
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement kedro-airflow (from versions: none)
ERROR: No matching distribution found for kedro-airflow
```

## Context

I would love to use some of the new typing features in 3.8.  Kedro appears to support 3.8, but kedro-airflow doesn't yet.

**Comment by 921kiyo** [comment]
Thank you for reporting! Seems like Airflow started supporting Python 3.8 recently, https://github.com/apache/airflow/pull/9804 so we will add Python 3.8 support as well :)

**Comment by 921kiyo** [comment]
Addressed this in https://github.com/quantumblacklabs/kedro-airflow/pull/63 Thank you for the request :)
