### ISSUE TITLE
ConfigLoader not being generated properly when running a kedro-airflow dag

### ISSUE THREAD

**Issue by JoaquinMusanti** [quantumblacklabs/kedro-airflow#75]
## Description
When running a DAG generated with kedro-airflow, the execution fails with the following error: kedro.framework.context.context.KedroContextError: Expected an instance of `ConfigLoader`, got `NoneType` instead.

## Steps to Reproduce

1. Create a new kedro pandas-iris project with `kedro new --starter=pandas-iris`
2. Create a dag for the project with `kedro airflow create`
3. Create a package for the project with `kedro package`
4. Add the necessary folders to the Airflow instance (data, conf, logs)
5. Install the package in the Airflow instance and run the dag

## Expected Result
The dag runs successfully

## Actual Result
The dag execution fails with an error

```
-- kedro.framework.context.context.KedroContextError: Expected an instance of `ConfigLoader`, got `NoneType` instead.
```

## Proposed Solution
Change the execute method in the dag from:

`def execute(self, context):`
`        with KedroSession.create(self.package_name,`
`                                 self.project_path,`
`                                 env=self.env) as session:`
`            session.run(self.pipeline_name, node_names=[self.node_name])`

to:

`def execute(self, context):`
`        configure_project(self.package_name)`
`        with KedroSession.create(self.package_name,`
`                                 self.project_path,`
`                                 env=self.env) as session:`
`            session.run(self.pipeline_name, node_names=[self.node_name])`

and add the following line to the dag imports

`from kedro.framework.project import configure_project`

## Your Environment

* Kedro-Airflow version 0.4.0
* Kedro version 0.17.2
* Airflow: Puckel docker image (puckel/docker-airflow:1.10.9)
* Python version 3.8.8
* Operating system and version: Running on WSL with Ubuntu 20.04

**Comment by limdauto** [comment]
@JoaquinMusanti Thank you very much for your report. We have released a new version with this bug fix included.
