### ISSUE TITLE
Please provide spaceflights tutorial

### ISSUE THREAD

**Issue by jacobweiss2305** [quantumblacklabs/kedro-airflow#84]
## Description
I am struggling to deploy the spaceflights tutorial into apache airflow using kedro-airflow. Could you please add a tutorial on this?

## Context
I am struggling to debug why the apache airflow job isn't running. I copied the dag into ~/airflow/dags/. I pip installed the kedro package, but am not getting a node to work in the run. It fails on the first node "preprocess-shuttles-node".

**Comment by limdauto** [comment]
@jacobweiss2305  Great. I will close this issue. Please feel free to re-open it if you need more assistance.
